name: Build and Push Docker Images

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Bước 1: Lấy code từ GitHub
      - name: Checkout code
        uses: actions/checkout@v3

      # Bước 2: Đăng nhập Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Bước 3: Pull MySQL và Push lên Docker Hub cá nhân
      - name: Pull MySQL and push to personal Docker Hub
        run: |
          docker pull mysql:8.0
          docker tag mysql:8.0 ${{ secrets.DOCKERHUB_USERNAME }}/portfolio-database:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/portfolio-database:latest

      # Bước 4: Build và Push Backend
      - name: Build and push Backend image
        uses: docker/build-push-action@v5
        with:
          context: ./nguyentranngochan
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/portfolio-backend:latest

      # Bước 5: Build và Push Frontend
      - name: Build and push Frontend image
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/portfolio-frontend:latest